name: alfresco-dbp
version: 2.0.0-SNAPSHOT
description: A Helm chart for the Alfresco Digital Business Platform
keywords:
- alfresco
- dbp
- platform
home: https://www.alfresco.com/platform
maintainers:
- name: Alfresco Platform Services Team
appVersion: 2.0-SNAPSHOT
